//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXAppTrade.Module.BusinessObjects.ORMDataModel1
{

    public partial class EquityTest : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        double fLastPrice;
        public double LastPrice
        {
            get { return fLastPrice; }
            set { SetPropertyValue<double>(nameof(LastPrice), ref fLastPrice, value); }
        }
        double fPercentageChange;
        [NonPersistent]
        public double PercentageChange
        {
            get { return fPercentageChange; }
            set { SetPropertyValue<double>(nameof(PercentageChange), ref fPercentageChange, value); }
        }
        [Association(@"PriceReferencesEquityTest")]
        public XPCollection<Price> Prices { get { return GetCollection<Price>(nameof(Prices)); } }

        
    }

}
