//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXAppTrade.Module.BusinessObjects.ORMDataModel1
{

    public partial class Price : XPObject
    {
        double fOpen;
        public double Open
        {
            get { return fOpen; }
            set { SetPropertyValue<double>(nameof(Open), ref fOpen, value); }
        }
        double fClose;
        public double Close
        {
            get { return fClose; }
            set { SetPropertyValue<double>(nameof(Close), ref fClose, value); }
        }
        double fLow;
        public double Low
        {
            get { return fLow; }
            set { SetPropertyValue<double>(nameof(Low), ref fLow, value); }
        }
        double fHigh;
        public double High
        {
            get { return fHigh; }
            set { SetPropertyValue<double>(nameof(High), ref fHigh, value); }
        }
        DateTime fDate;
        [ColumnDefaultValue("17.09.2021 00:00:00")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        EquityTest fEquityTest;
        [Association(@"PriceReferencesEquityTest")]
        public EquityTest EquityTest
        {
            get { return fEquityTest; }
            set { SetPropertyValue<EquityTest>(nameof(EquityTest), ref fEquityTest, value); }
        }
    }

}
